### ISSUE TITLE
Frontend: Not-Human Classification also updates Bar Charts

### ISSUE THREAD

**Issue by leriomaggio** [DynamicGenetics/The-Learning-Machine#4]
Dragging a face to "not-human" also updates the bar charts of performance. 
We should check this out when we'll link backend integration.

Branch: `launch`

**Comment by OliverDavis** [comment]
Yes, although it won't update the fit of the model, presumably, it uses the same function to call the back end and returns the same data structure, so my thought is we follow the expected behaviour of moving on the bar chart when dragging the face. The fact that the model fit doesn't change is really a learning point.
