### ISSUE TITLE
Frontend: faces could go beyond new hexagon boundaries

### ISSUE THREAD

**Issue by leriomaggio** [DynamicGenetics/The-Learning-Machine#5]
**First** public shout out to @OliverDavis  for the new improvements to the **UI** (see _branch_: `launch`) 
It is simply *OUTSTANDING* 🤩 

(See screenshots below - cc/ @ninadicara )

<img width="1611" alt="Screenshot 2021-10-22 at 18 50 38" src="https://user-images.githubusercontent.com/1908453/138493257-ff279386-7e27-4acf-9a8b-d87f9afde50b.png">

<img width="1609" alt="Screenshot 2021-10-22 at 18 54 39" src="https://user-images.githubusercontent.com/1908453/138493828-45660a76-2372-436d-ad6e-f3d9c4f0c5f4.png">

Also (from Screenshot 1): 
faces should be constrained within the new Hexagon Boundaries.

**Comment by OliverDavis** [comment]
If this is working correctly the faces should more-or-less be constrained within the hexagon because the forces should be pulling towards the targets, so the furthest that this can take them is directly between two targets. However, the faces also repel each other, so this could be pushing them over the line. I don't think this is necessarily a problem, so long as the mechanism is working as intended. I'll check.
